// Generated by scripts/scanner_identity.py; do not edit.
export const SCANNER_IDENTITY = {'engineVersion': 'sha256:bdd3fea838d0441b030fb54ffcc7eb5484c11f2c7ee51812d5ea37f2b88d05aa', 'conditionContractHash': '48565c0b71caa01ed419f54e77c6d60e1b67e279f27d302cb3eddcfb3d890ef3'} as const;
export function assertScannerIdentity(value: unknown): void {
  const identity = value as Partial<typeof SCANNER_IDENTITY> | null;
  if (identity?.engineVersion !== SCANNER_IDENTITY.engineVersion
      || identity?.conditionContractHash !== SCANNER_IDENTITY.conditionContractHash)
    throw new Error('Scanner engine or condition contract is incompatible. Refresh after the matching release is deployed.');
}
