// Generated by scripts/scanner_identity.py; do not edit.
export const SCANNER_IDENTITY = {'engineVersion': 'sha256:8013351008f2c6a09792a073d8f4246ba910b2f937d966a628a21ea5a5f14306', 'conditionContractHash': 'c1a0e79f4396c02532874aa8a91c07fd28e83fd102599cdf8788ec36f4b92b85'} as const;
export function assertScannerIdentity(value: unknown): void {
  const identity = value as Partial<typeof SCANNER_IDENTITY> | null;
  if (identity?.engineVersion !== SCANNER_IDENTITY.engineVersion
      || identity?.conditionContractHash !== SCANNER_IDENTITY.conditionContractHash)
    throw new Error('Scanner engine or condition contract is incompatible. Refresh after the matching release is deployed.');
}
